### PR TITLE
Force LTR for latex (normal and inline)

### PR DESCRIPTION
**Pull request by giladwo**
This patch ensures latex (katex) is always LTR ands sets directions of properties individually.

A few (possibly redundant) helpers are introduced to make everything clearer and let newcomers easily adjust the behavior to their needs.

### CODE REVIEW

**Comment by benjypng** [comment]
Apologies, could you share the specific issue that this PR is trying to solve?

**Comment by giladwo** [comment]
> Apologies, could you share the specific issue that this PR is trying to solve?


Of course, here's the same theorem in 3 versions:
English:
image

Hebrew:
image
As can be seen, the rendered latex is backwards and completely unusable (and all properties are forced to the same direction, which is arguably worse than having them on different sides).

Hebrew (with the PR's latex & property fix):
image
Now the latex is rendered correctly :tada:

**Comment by benjypng** [comment]
Please test with this:

```
const observer = new top.MutationObserver(() => {
  const allElems = top?.document.querySelectorAll(".ls-block");
  if (allElems && allElems.length > 0) {
    for (const elem of allElems) {
      elem.setAttribute("dir", "auto");
    }
  }
  const latexElems = top?.document.querySelectorAll(".katex-html");
  if (latexElems && latexElems.length > 0) {
    for (const elem of latexElems) {
      elem.setAttribute("dir", "ltr");
    }
  }
});

observer.observe(top.document.getElementById("app-container"), {
  attributes: false,
  childList: true,
  subtree: true,
});
```

**Comment by giladwo** [comment]
> Please test with this:

This seems to work as well (slightly surprisingly because I'm pretty sure I've tried setting just ".katex-html" to "ltr").

I'd still extract the commonality out.

**Pull request closed without merging**
